font_family Hack Nerd Font
font_size 14.0
cursor_shape block
cursor_blink_interval 0
cursor_trail 1
cursor_trail_decay 0.05 0.2
cursor_trail_start_threshold 4
window_margin_width 8
hide_window_decorations titlebar-only
placement_strategy center
shell_integration disabled
background_opacity 0.87
close_on_child_death no

#: Custom tmux keybinds
#: --------------------
#: create new window
map cmd+t send_text all \u0018c
#: kill window
map cmd+w send_text all \u0018k
#: search up
map cmd+f send_text all \u0018[?
#: next window
map ctrl+tab send_text all \u0018n
#: previous window
map ctrl+shift+tab send_text all \u0018p



# Nightfox colors for Kitty
## name: carbonfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/carbonfox/kitty.conf

background #161616
foreground #f2f4f8
selection_background #2a2a2a
selection_foreground #f2f4f8
cursor_text_color #161616
url_color #25be6a

# Cursor
# uncomment for reverse background
# cursor none
cursor #f2f4f8

# Border
active_border_color #78a9ff
inactive_border_color #535353
bell_border_color #3ddbd9

# Tabs
active_tab_background #78a9ff
active_tab_foreground #0c0c0c
inactive_tab_background #2a2a2a
inactive_tab_foreground #6e6f70

# normal
color0 #282828
color1 #ee5396
color2 #25be6a
color3 #08bdba
color4 #78a9ff
color5 #be95ff
color6 #33b1ff
color7 #dfdfe0

# bright
color8 #484848
color9 #f16da6
color10 #46c880
color11 #2dc7c4
color12 #8cb6ff
color13 #c8a5ff
color14 #52bdff
color15 #e4e4e5

# extended colors
color16 #3ddbd9
color17 #ff7eb6


# # gruvbox dark by morhetz, https://github.com/morhetz/gruvbox
# # This work is licensed under the terms of the MIT license.
# # For a copy, see https://opensource.org/licenses/MIT.
# 
# # 235_bg, 223_fg1
# background #282828
# foreground #ebdbb2
# 
# # 245_gray, 237_bg1
# selection_foreground #928374
# selection_background #3c3836
# 
# # 229_fg0, 236_bg0_s
# cursor            #fbf1c7
# cursor_text_color #32302f
# 
# # 208_orange
# url_color #fe8019
# 
# # 235_bg, 241_bg3
# color0 #282828
# color8 #665c54
# 
# # 124_red, 167_red
# color1 #cc241d
# color9 #fb4934
# 
# # 106_green, 142_green
# color2  #98971a
# color10 #b8bb26
# 
# # 172_yellow, 214_yellow
# color3  #d79921
# color11 #fabd2f
# 
# # 72_aqua, 109_blue
# color4  #689d6a
# color12 #83a598
# 
# # 132_purple, 175_purple
# color5  #b16286
# color13 #d3869b
# 
# # 72_aqua, 108_aqua
# color6  #689d6a
# color14 #8ec07c
# 
# # 246_gray, 245_gray
# color7  #a89984
# color15 #928374


