[env]
TERM="alacritty"

[window.padding]
x= 8
y= 8

[window]
opacity=1
#startup_mode="Fullscreen"
decorations="Buttonless"
dynamic_padding=true

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 14

[font.normal]
family ="Menlo"
style = "Regular"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u0018n" # tmux next pane

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u0018p" # tmux prev pane

[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0018c" # tmux new pane

[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u0018x" # tmux close pane

[[keyboard.bindings]]
key = "F"
mods = "Command"
chars = "\u0018[?" # tmux search up

