[env]
TERM="alacritty"

[window.padding]
x= 16
y= 16

[window]
opacity=0.90
#startup_mode="Fullscreen"
decorations="Buttonless"
dynamic_padding=true

[font]
size = 14

[font.normal]
family ="Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u0018n" # tmux next pane

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u0018p" # tmux prev pane

[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0018c" # tmux new pane

[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u0018x" # tmux close pane

[[keyboard.bindings]]
key = "F"
mods = "Command"
chars = "\u0018[?" # tmux search up
