#!/usr/bin/env sh

# load scripting additions (optional)
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# new window spawns to the right if vertical split, or bottom if horizontal split
# yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 5
yabai -m config bottom_padding 40
yabai -m config left_padding 25
yabai -m config right_padding 25
yabai -m config window_gap 15

# -- mouse settings --

# center mouse on window with focus
yabai -m config mouse_follows_focus off

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier ctrl
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder" manage=off

# Sketchybar settings
yabai -m config external_bar all:$(sketchybar --query bar | jq .height):0

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# transparency
#yabai -m config window_opacity on
#yabai -m config active_window_opacity 0.50
#yabai -m config normal_window_opacity 0.2
