#!/usr/bin/env sh

# padding set to 12px
yabai -m config top_padding -2
yabai -m config bottom_padding 4
yabai -m config left_padding 4
yabai -m config right_padding 4
yabai -m config window_gap 4

# -- mouse settings --

# center mouse on window with focus
yabai -m config mouse_follows_focus off

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier ctrl
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder" manage=off

# Sketchybar settings
yabai -m config external_bar all:$(sketchybar --query bar | jq .height):0

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# transparency
#yabai -m config window_opacity on
#yabai -m config active_window_opacity 0.50
#yabai -m config normal_window_opacity 0.2

# purple/green based
#borders active_color=0xff9ed072 inactive_color=0xffb39df3 width=7.0 &

# yellow (graphene) based
borders active_color=0xFFFFD966 inactive_color=0x66FFD966 width=7.0 
